export { defineTool } from "./tools"
export { createComputerUseClient, AllternitComputerUseClient } from "./computer-use"
export type AssetRef = string | { asset_id: string }

/**
 * Allternit Platform Client
 */
export function createAllternitClient(config: any = {}) {
  // This is a bridge to the generated client logic
  // In a real build, this would be generated by script/build.ts
  return {
    sessions: {
      create: async () => ({ id: 'new-session' }),
      get: async (id: string) => ({ id }),
    }
  }
}

export const createAllternit = createAllternitClient;
